<a href="https://colab.research.google.com/github/Rashvi/GFG_ML/blob/main/GFGML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#creating array from python list
list1 = [2,4,6,8,10]
arr1 = np.array(list)

In [8]:
arr1
type(arr1)

numpy.ndarray

In [7]:
list1
type(list1)

list

In [9]:
#converting list to array 
list1 = [[2,4,6],
         [3,5,7]]
arr1 = np.array(list1);         

In [11]:
#float array
arr2 = np.array(arr1 , dtype = 'float')
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [14]:
# array to list
list2 = arr2.tolist();
list2

[[2.0, 4.0, 6.0], [3.0, 5.0, 7.0]]

#Array Diamensions

In [18]:
arr2.shape
arr2.size

6

# Reversing rows and columns

In [19]:
#reversing row
arr2[::-1]

array([[3., 5., 7.],
       [2., 4., 6.]])

In [20]:
#reverse the columns
arr2[::,::-1]

array([[6., 4., 2.],
       [7., 5., 3.]])

In [21]:
#reerse both row and columns
arr2[::-1,::-1]

array([[7., 5., 3.],
       [6., 4., 2.]])

# Specific Elements Extraction

In [23]:
#all the columns element but from 1 row
arr1[0,:]
#it is equivalent to 
arr1[:1,:]

array([[2, 4, 6]])

#Basic Statistics 


In [24]:
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [25]:
arr2.min()

2.0

In [26]:
arr2.max()

7.0

In [27]:
arr2.sum()

27.0

In [31]:
arr2.mean()
#or
np.average(arr2)

4.5

In [30]:
np.median(arr2)

4.5

In [33]:
#to get varience
np.var(arr2)

2.9166666666666665

#Reshaping and Flattening

In [36]:
arr2.shape

(2, 3)

In [37]:
arr2.reshape(3,2)
#but number of elements should be equal

array([[2., 4.],
       [6., 3.],
       [5., 7.]])

In [38]:
arr2.reshape(6)

array([2., 4., 6., 3., 5., 7.])

In [39]:
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [40]:
#to have single diamension
f1 = arr2.flatten();

In [41]:
f1

array([2., 4., 6., 3., 5., 7.])

#creating random arrays and sequences

In [43]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#we can even give step size
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [47]:
#printing in reverse order
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [48]:
#linspace automatically calculate the stepsize. we have to just give start,end and total elements
arr = np.linspace(0,10,5)
arr  

array([ 0. ,  2.5,  5. ,  7.5, 10. ])