<a href="https://colab.research.google.com/github/Rashvi/GFG_ML/blob/main/GFGML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#creating array from python list
list1 = [2,4,6,8,10]
arr1 = np.array(list)

In [8]:
arr1
type(arr1)

numpy.ndarray

In [7]:
list1
type(list1)

list

In [9]:
#converting list to array 
list1 = [[2,4,6],
         [3,5,7]]
arr1 = np.array(list1);         

In [11]:
#float array
arr2 = np.array(arr1 , dtype = 'float')
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [14]:
# array to list
list2 = arr2.tolist();
list2

[[2.0, 4.0, 6.0], [3.0, 5.0, 7.0]]

#Array Diamensions

In [18]:
arr2.shape
arr2.size

6

# Reversing rows and columns

In [19]:
#reversing row
arr2[::-1]

array([[3., 5., 7.],
       [2., 4., 6.]])

In [20]:
#reverse the columns
arr2[::,::-1]

array([[6., 4., 2.],
       [7., 5., 3.]])

In [21]:
#reerse both row and columns
arr2[::-1,::-1]

array([[7., 5., 3.],
       [6., 4., 2.]])

# Specific Elements Extraction

In [23]:
#all the columns element but from 1 row
arr1[0,:]
#it is equivalent to 
arr1[:1,:]

array([[2, 4, 6]])

#Basic Statistics 
