<a href="https://colab.research.google.com/github/Rashvi/GFG_ML/blob/main/GFGML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#creating array from python list
list1 = [2,4,6,8,10]
arr1 = np.array(list)

In [ ]:
arr1
type(arr1)

numpy.ndarray

In [ ]:
list1
type(list1)

list

In [ ]:
#converting list to array 
list1 = [[2,4,6],
         [3,5,7]]
arr1 = np.array(list1);         

In [ ]:
#float array
arr2 = np.array(arr1 , dtype = 'float')
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [ ]:
# array to list
list2 = arr2.tolist();
list2

[[2.0, 4.0, 6.0], [3.0, 5.0, 7.0]]

#Array Diamensions

In [ ]:
arr2.shape
arr2.size

6

# Reversing rows and columns

In [ ]:
#reversing row
arr2[::-1]

array([[3., 5., 7.],
       [2., 4., 6.]])

In [ ]:
#reverse the columns
arr2[::,::-1]

array([[6., 4., 2.],
       [7., 5., 3.]])

In [ ]:
#reerse both row and columns
arr2[::-1,::-1]

array([[7., 5., 3.],
       [6., 4., 2.]])

# Specific Elements Extraction

In [ ]:
#all the columns element but from 1 row
arr1[0,:]
#it is equivalent to 
arr1[:1,:]

array([[2, 4, 6]])

#Basic Statistics 


In [ ]:
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [ ]:
arr2.min()

2.0

In [ ]:
arr2.max()

7.0

In [ ]:
arr2.sum()

27.0

In [ ]:
arr2.mean()
#or
np.average(arr2)

4.5

In [ ]:
np.median(arr2)

4.5

In [ ]:
#to get varience
np.var(arr2)

2.9166666666666665

#Reshaping and Flattening

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr2.reshape(3,2)
#but number of elements should be equal

array([[2., 4.],
       [6., 3.],
       [5., 7.]])

In [ ]:
arr2.reshape(6)

array([2., 4., 6., 3., 5., 7.])

In [ ]:
arr2

array([[2., 4., 6.],
       [3., 5., 7.]])

In [ ]:
#to have single diamension
f1 = arr2.flatten();

In [ ]:
f1

array([2., 4., 6., 3., 5., 7.])

#creating random arrays and sequences

In [ ]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#we can even give step size
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [ ]:
#printing in reverse order
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
#linspace automatically calculate the stepsize. we have to just give start,end and total elements
arr = np.linspace(0,10,5)
arr  

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr = np.zeros([2,4,6])
arr

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

#unique items and counts

In [ ]:
arr = [1, 5, 7, 9, 3]
type(arr)

list

In [ ]:
#unique values and count of unique value
val , count = np.unique(arr2,return_counts=True)

In [ ]:
val

array([2., 3., 4., 5., 6., 7.])

In [ ]:
count

array([1, 1, 1, 1, 1, 1])

#DataFrames

In [ ]:
import pandas as pd
import numpy as np

In [ ]:

data = {
    'roll':[1,2,3,4],
    'p_id':[2,4,5,6],
    'marks':[89,90,79,80]
}
data

{'marks': [89, 90, 79, 80], 'p_id': [2, 4, 5, 6], 'roll': [1, 2, 3, 4]}

In [ ]:
# creating dataFrame
df = pd.DataFrame(data)

In [ ]:
df

roll  p_id  marks
0     1     2     89
1     2     4     90
2     3     5     79
3     4     6     80

In [ ]:
#setting the index
df = pd.DataFrame(data , index=['xy','pq','ab','rs'])

In [ ]:
df

roll  p_id  marks
xy     1     2     89
pq     2     4     90
ab     3     5     79
rs     4     6     80

In [ ]:
#extracting infomation
df.loc['rs']


roll      4
p_id      6
marks    80
Name: rs, dtype: int64

In [ ]:
df.iloc[2:,:-1]

roll  p_id
ab     3     5
rs     4     6

#Working on CVS

In [16]:
#loading data
import pandas as pd
import numpy as py
df = pd.read_csv('/content/iris_dataset.csv')
df.head(20)

sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2
11           4.8          3.4           1.6          0.2
12           4.8          3.0           1.4          0.1
13           4.3          3.0           1.1          0.1
14           5.8          4.0           1.2          0.2
15           5.7          4.4           1.5          0.4
16           5.4          3.9           1.3          0.4
17           5.1          3.5           1.4          0.3
18           5.7          3.8           1.7          0.3
19           5.1          3.8           1.5          0.3

In [7]:
#to know the information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [8]:
#data description
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
#data Selection
df['sepal_width'][:5]

0    3.5
1    3.0
2    3.2
3    3.1
4    3.6
Name: sepal_width, dtype: float64

In [10]:
#to print data in the form of dataframe

df[['sepal_width']][:5]

sepal_width
0          3.5
1          3.0
2          3.2
3          3.1
4          3.6

In [13]:
df[['sepal_width','petal_width']][:5]

sepal_width  petal_width
0          3.5          0.2
1          3.0          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2

In [14]:
df.iloc[:10,1:3]

sepal_width  petal_length
0          3.5           1.4
1          3.0           1.4
2          3.2           1.3
3          3.1           1.5
4          3.6           1.4
5          3.9           1.7
6          3.4           1.4
7          3.4           1.5
8          2.9           1.4
9          3.1           1.5

In [15]:
df.iloc[:10,[1,3]]

sepal_width  petal_width
0          3.5          0.2
1          3.0          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2
5          3.9          0.4
6          3.4          0.3
7          3.4          0.2
8          2.9          0.2
9          3.1          0.1

#missing Value